### ISSUE TITLE
Broken with 0.7.2

### ISSUE THREAD

**Issue by EugenMayer** [sous-chefs/vagrant-cookbook#84] opened 2018-04-03 06:29 UTC
# Description

Installing 0.7.2 fails

# ChefDK Version

2.5.3

# Platform Version

OSX sierra

# Replication Case

Somehow i cannot reproduce it this way:

Berksfile

```
source 'https://supermarket.chef.io'

cookbook 'vagrant'
```

```
chef exec berks vendor cookbooks
```

while this will work

Berkfile
```
source 'https://supermarket.chef.io'
cookbook 'vagrant',  '<= 0.7.1'
```

# Stacktrace

```
/opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/package/tar_header.rb:128:in `strict_oct': "\x80\x00\x00\x00d\x9E\xD3\xD9" is not an octal string (ArgumentError)
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/package/tar_header.rb:108:in `from'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/package/tar_reader.rb:59:in `each'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive/tar.rb:27:in `block in extract'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/package/tar_reader.rb:29:in `new'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive/tar.rb:118:in `reader'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive/tar.rb:25:in `extract'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/mixlib-archive-0.4.1/lib/mixlib/archive.rb:33:in `extract'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/community_rest.rb:16:in `unpack'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/community_rest.rb:102:in `download'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/downloader.rb:70:in `try_download'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/downloader.rb:40:in `block in download'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/downloader.rb:39:in `each'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/downloader.rb:39:in `download'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/installer.rb:108:in `install'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/berkshelf-6.3.1/lib/berkshelf/installer.rb:181:in `block (2 levels) in install_from_universe'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
```

**Comment by MarkGibbons** [comment] 2018-04-07 04:40
@EugenMayer 

Could you tell me for sure what fails?  Your comments above are a little confusing.  I'm running chefdk 2.4.17 and have had other problems trying to use chefdk 2.5.  Using 2.4.17, everything I can think to try from above has worked.

Regards,
Mark

**Comment by EugenMayer** [comment] 2018-04-07 07:12
All i can say you, with the current chefDK you cannot use berks to get vargant 0.7.2, but it works with 0.7.1 - i cannot provide more then above, sorry (i do not have anything more)

Obviously changes for 0.7.2 seems have cause that

**Comment by cheeseplus** [comment] 2018-04-09 11:48
This looks like a berkshelf problem, not one with the cookbook itself.

**Comment by EugenMayer** [comment] 2018-04-09 12:06
You mean without any berks update done, and 0.7.1 working with the current "updated" berks - and every single other cookbook working with the current berk ( about 60 ) you really consider this being a bug in berks? I mean, at least one other would fail too, wouldnt it?

Without understanding the error, the implementation of vagrant or berks, this is extremely unlikely, isnt it?

**Comment by MarkGibbons** [comment] 2018-04-09 13:31
Hi @EugenMayer 
  I did install chefdk 2.5.3 and test the command you indicated had a problem. I vendored the 0.7.2 version without a problem.  I needed two attempts to get 2.5.3 installed without leftovers from a previous chefdk install, I had to wipe out ~/.chefdk.  But in that situation it failed for every cookbook when it failed for 0.7.2.  I have some fixes coming up.  We'll see what happens in the next version.

Mark

**Comment by EugenMayer** [comment] 2018-04-09 13:36
@MarkGibbons are you directing into an issue with the upgrade of chefdk ( so i have an unclean upgrade state ) and thats the root of the cause or could you reproduce that actual issue with the vagrant cookbook? thanks for looking at this one

**Comment by EugenMayer** [comment] 2018-04-09 14:26
Do you want to fix the root of the cause or want me to just flush `~/.chefdk` / clean state install chefdk and ignore the issue.

I could do both, but if you would like to fix it, i keep the current state for reproduction / analysis to help you guys find the cause.

**Comment by cheeseplus** [comment] 2018-04-09 14:30
There is nothing to fix in the cookbook for this problem - the root cause is a RubyGems bug upstream.

**Comment by MarkGibbons** [comment] 2018-04-25 22:41
@EugenMayer 

Berkshelf has a discussion of the problem and possibly a link to a fix.  I'm going to close this issue as its cause is not related to the vagrant cookbook. I've seen this a handful of times now on a variety of other cookbooks.  I hope this link might help you.

https://github.com/berkshelf/berkshelf/issues/1744

Regards,
  Mark

**Closed by MarkGibbons** 2018-04-25 22:41 UTC

**Comment by EugenMayer** [comment] 2018-04-26 05:05
thank you mark
